name: $(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - 'master'

pool:
  vmImage: 'VS2017-Win2016'

variables:
  pesterScript: $(System.DefaultWorkingDirectory)\PipelinesAsCode.Tests.ps1
  pesterOutput: $(System.DefaultWorkingDirectory)\Test-Pester.XML

steps:
- powershell: |
    Install-Module -Name Pester -Force -SkipPublisherCheck
  displayName: Install Pester

- powershell: |
    Import-Module Pester
    Invoke-Pester -Script $(pesterScript) -OutputFile $(pesterOutput) -OutputFormat NUnitXML
    
    $failures = ([xml](Get-Content $(pesterOutput))).'test-results'.failures

    if ($failures -gt 0) 
    { 
      throw "$failures tests failed."
    }
  displayName: Run Pester Tests

- task: PublishTestResults@2
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: $(pesterOutput)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'